# Destination S3 prefix
dst_data_prefix = "inputs"

# Output filename
output_file_name = "buyer_stage_input"

# Day partitions
day_partitions = 't001-t007-t030-t060-t090'

# Repartition number
repartition_num = 600

# Test data S3 bucket
test_data_prefix = 'etl_pipeline_test'

# Sampling percentage for testing purposes
sample_percentage = 0.001

# Default values
default_integer = 0
default_dwell_threshhold = 180

# Columns with null values
cols_with_nulls = ['total_ldp_page_views','median_ldp_page_views','average_ldp_page_views',
                   'total_distinct_listings_viewed','total_listings_viewed','total_saved_listings','total_shared_listings','total_saved_searches',
                   'total_shared_searches','total_searches','median_searches','average_searches',
                   'total_leads_submitted','submitted_leads_for_rent','submitted_leads_for_sale',
                   'submitted_leads_not_for_sale']

# Columns with outliers
cols_with_outliers = ['average_ldp_dwell_time_seconds','total_ldp_dwell_time_seconds','median_ldp_dwell_time_seconds',
                      'total_srp_dwell_time_seconds','average_srp_dwell_time_seconds','median_srp_dwell_time_seconds',
                      'total_lead_dwell_time_seconds','average_lead_dwell_time_seconds','median_lead_dwell_time_seconds']

# Columns and their options to one hot encode
# cols_options_to_one_hot_encode = {'ldp_dominant_segment': ['for sale','not for sale','for rent','no_segment'],
#                                   'ldp_dominant_experience_type': ['web','mobile apps','mobile web','others'],
#                                   'ldp_dominant_apps_type': ['ios core apps','android core apps','ios rentals apps','android rentals apps','others'],
#                                   'srp_dominant_experience_type': ['web','mobile web'],
#                                   'srp_dominant_apps_type': ['others']}
cols_options_to_one_hot_encode = {'ldp_dominant_segment': ['for sale','not for sale','for rent','no_segment']}

# Columns to drop
cols_to_drop = [
	'minimum_maximum_search_number_of_bathrooms','srp_dominant_site_section','ldp_dominant_city','ldp_dominant_state',
    'is_registered_user','ldp_dominant_zip','ldp_page_views_for_sale','ldp_page_views_for_rent',
    'ldp_page_views_others','ldp_page_views_not_for_sale','minimum_ldp_dwell_time_seconds',
    'maximum_ldp_dwell_time_seconds','most_recent_ldp_visit_date','first_ldp_visit_date',
    'median_ldp_listing_number_of_bath_rooms','median_ldp_listing_number_of_bed_rooms',
    'median_ldp_listing_number_of_stories','median_ldp_listing_current_price',
    'average_ldp_listing_number_of_bath_rooms','average_ldp_listing_number_of_bed_rooms',
    'average_listing_number_of_stories','average_ldp_listing_current_price',
    'standard_deviation_ldp_listing_number_of_bath_rooms','standard_deviation_ldp_listing_number_of_bed_rooms',
    'standard_deviation_listing_number_of_stories','standard_deviation_ldp_listing_current_price',
    'median_ldp_listing_original_price','average_ldp_listing_original_price',
    'standard_deviation_ldp_listing_original_price','ldp_dominant_property_type','ldp_dominant_listing_type',
    'srp_dominant_city','srp_dominant_state','srp_dominant_zip','srp_recent_city','srp_recent_state',
    'srp_recent_zip','median_search_min_price','average_search_min_price','minimum_search_min_price',
    'maximum_search_min_price','median_search_max_price','average_search_max_price','minimum_search_max_price',
    'maximum_search_max_price','median_minimum_search_number_of_bedrooms',
    'average_minimum_search_number_of_bedrooms','minimum_search_number_of_bedrooms',
    'maximum_minimum_search_number_of_bedrooms','average_maximum_search_number_of_bedrooms',
    'minimum_maximum_search_number_of_bedrooms','maximum_search_number_of_bedrooms',
    'median_maximum_search_number_of_bedrooms','average_minimum_search_number_of_bathrooms',
    'minimum_search_number_of_bathrooms','maximum_minimum_search_number_of_bathrooms',
    'median_minimum_search_number_of_bathrooms','average_maximum_search_number_of_bathrooms',
    'maximum_search_number_of_bathrooms','maximum_maximum_search_number_of_bathrooms',
    'median_maximum_search_number_of_bathrooms','minimum_srp_dwell_time_seconds',
    'maximum_srp_dwell_time_seconds','most_recent_srp_visit_date','first_srp_visit_date',
    'submitted_leads_advpro','submitted_leads_basic','submitted_leads_connection_for_buyers',
    'minimum_lead_dwell_time_seconds','maximum_lead_dwell_time_seconds','most_recent_lead_submitted',
    'leads_dominant_site_section','leads_dominant_lead_category_group','leads_dominant_experience_type',
    'leads_dominant_apps_type','number_of_visits','run_date_mst_yyyymmdd'
]

# Expected output columns, in correct order
expected_output_cols = [
    'member_id',
    'snapshot_month',
    'snapshot_day_of_month',
    'snapshot_day_of_week',
    'ldp_dominant_segment_for_sale_001',
    'ldp_dominant_segment_not_for_sale_001',
    'ldp_dominant_segment_for_rent_001',
    'ldp_dominant_segment_no_segment_001',
    'total_ldp_page_views_001',
    'median_ldp_page_views_001',
    'average_ldp_page_views_001',
    'average_ldp_dwell_time_seconds_001',
    'total_ldp_dwell_time_seconds_001',
    'median_ldp_dwell_time_seconds_001',
    'total_distinct_listings_viewed_001',
    'total_listings_viewed_001',
    #'median_distinct_listings_viewed_001',
    #'average_distinct_listings_viewed_001',
    'median_listings_viewed_001',
    'average_listings_viewed_001',
    #'ldp_dominant_experience_type_web_001',
    #'ldp_dominant_experience_mobile_app_encoded_001',
    #'ldp_dominant_experience_type_mobile_web_001',
    #'ldp_dominant_experience_type_others_001',
    #'ldp_dominant_apps_type_ios_core_apps_001',
    #'ldp_dominant_apps_type_android_core_apps_001',
    #'ldp_dominant_apps_type_ios_rentals_apps_001',
    #'ldp_dominant_apps_type_android_rentals_apps_001',
    #'ldp_dominant_apps_type_others_001',
    'total_searches_001',
    'median_searches_001',
    'average_searches_001',
    'total_srp_dwell_time_seconds_001',
    'average_srp_dwell_time_seconds_001',
    'median_srp_dwell_time_seconds_001',
    'total_lead_dwell_time_seconds_001',
    'average_lead_dwell_time_seconds_001',
    'median_lead_dwell_time_seconds_001',
    'total_saved_listings_001',
    'total_shared_listings_001',
    'total_saved_searches_001',
    'total_shared_searches_001',
    #'srp_dominant_experience_type_web_001',
    #'srp_dominant_experience_type_mobile_web_001',
    #'srp_dominant_apps_type_others_001',
    'total_leads_submitted_001',
    'submitted_leads_for_rent_001',
    'submitted_leads_for_sale_001',
    'submitted_leads_not_for_sale_001',
    'ldp_dominant_segment_for_sale_007',
    'ldp_dominant_segment_not_for_sale_007',
    'ldp_dominant_segment_for_rent_007',
    'ldp_dominant_segment_no_segment_007',
    'total_ldp_page_views_007',
    'median_ldp_page_views_007',
    'average_ldp_page_views_007',
    'average_ldp_dwell_time_seconds_007',
    'total_ldp_dwell_time_seconds_007',
    'median_ldp_dwell_time_seconds_007',
    'total_distinct_listings_viewed_007',
    'total_listings_viewed_007',
    #'median_distinct_listings_viewed_007',
    #'average_distinct_listings_viewed_007',
    'median_listings_viewed_007',
    'average_listings_viewed_007',
    #'ldp_dominant_experience_type_web_007',
    #'ldp_dominant_experience_mobile_app_encoded_007',
   # 'ldp_dominant_experience_type_mobile_web_007',
    #'ldp_dominant_experience_type_others_007',
    #'ldp_dominant_apps_type_ios_core_apps_007',
    #'ldp_dominant_apps_type_android_core_apps_007',
   # 'ldp_dominant_apps_type_ios_rentals_apps_007',
    #'ldp_dominant_apps_type_android_rentals_apps_007',
    #'ldp_dominant_apps_type_others_007',
    'total_searches_007',
    'median_searches_007',
    'average_searches_007',
    'total_srp_dwell_time_seconds_007',
    'average_srp_dwell_time_seconds_007',
    'median_srp_dwell_time_seconds_007',
    'total_lead_dwell_time_seconds_007',
    'average_lead_dwell_time_seconds_007',
    'median_lead_dwell_time_seconds_007',
    'total_saved_listings_007',
    'total_shared_listings_007',
    'total_saved_searches_007',
    'total_shared_searches_007',
    #'srp_dominant_experience_type_web_007',
    #'srp_dominant_experience_type_mobile_web_007',
    #'srp_dominant_apps_type_others_007',
    'total_leads_submitted_007',
    'submitted_leads_for_rent_007',
    'submitted_leads_for_sale_007',
    'submitted_leads_not_for_sale_007',
    'ldp_dominant_segment_for_sale_030',
    'ldp_dominant_segment_not_for_sale_030',
    'ldp_dominant_segment_for_rent_030',
    'ldp_dominant_segment_no_segment_030',
    'total_ldp_page_views_030',
    'median_ldp_page_views_030',
    'average_ldp_page_views_030',
    'average_ldp_dwell_time_seconds_030',
    'total_ldp_dwell_time_seconds_030',
    'median_ldp_dwell_time_seconds_030',
    'total_distinct_listings_viewed_030',
    'total_listings_viewed_030',
    #'median_distinct_listings_viewed_030',
    #'average_distinct_listings_viewed_030',
    'median_listings_viewed_030',
    'average_listings_viewed_030',
    #'ldp_dominant_experience_type_web_030',
    #'ldp_dominant_experience_mobile_app_encoded_030',
    #'ldp_dominant_experience_type_mobile_web_030',
    #'ldp_dominant_experience_type_others_030',
    #'ldp_dominant_apps_type_ios_core_apps_030',
    #'ldp_dominant_apps_type_android_core_apps_030',
   # 'ldp_dominant_apps_type_ios_rentals_apps_030',
    #'ldp_dominant_apps_type_android_rentals_apps_030',
    #'ldp_dominant_apps_type_others_030',
    'total_searches_030',
    'median_searches_030',
    'average_searches_030',
    'total_srp_dwell_time_seconds_030',
    'average_srp_dwell_time_seconds_030',
    'median_srp_dwell_time_seconds_030',
    'total_lead_dwell_time_seconds_030',
    'average_lead_dwell_time_seconds_030',
    'median_lead_dwell_time_seconds_030',
    'total_saved_listings_030',
    'total_shared_listings_030',
    'total_saved_searches_030',
    'total_shared_searches_030',
    #'srp_dominant_experience_type_web_030',
    #'srp_dominant_experience_type_mobile_web_030',
    #'srp_dominant_apps_type_others_030',
    'total_leads_submitted_030',
    'submitted_leads_for_rent_030',
    'submitted_leads_for_sale_030',
    'submitted_leads_not_for_sale_030',
    'ldp_dominant_segment_for_sale_060',
    'ldp_dominant_segment_not_for_sale_060',
    'ldp_dominant_segment_for_rent_060',
    'ldp_dominant_segment_no_segment_060',
    'total_ldp_page_views_060',
    'median_ldp_page_views_060',
    'average_ldp_page_views_060',
    'average_ldp_dwell_time_seconds_060',
    'total_ldp_dwell_time_seconds_060',
    'median_ldp_dwell_time_seconds_060',
    'total_distinct_listings_viewed_060',
    'total_listings_viewed_060',
    #'median_distinct_listings_viewed_060',
    #'average_distinct_listings_viewed_060',
    'median_listings_viewed_060',
    'average_listings_viewed_060',
    #'ldp_dominant_experience_type_web_060',
    #'ldp_dominant_experience_mobile_app_encoded_060',
    #'ldp_dominant_experience_type_mobile_web_060',
    #'ldp_dominant_experience_type_others_060',
    #'ldp_dominant_apps_type_ios_core_apps_060',
    #'ldp_dominant_apps_type_android_core_apps_060',
    #'ldp_dominant_apps_type_ios_rentals_apps_060',
    #'ldp_dominant_apps_type_android_rentals_apps_060',
    #'ldp_dominant_apps_type_others_060',
    'total_searches_060',
    'median_searches_060',
    'average_searches_060',
    'total_srp_dwell_time_seconds_060',
    'average_srp_dwell_time_seconds_060',
    'median_srp_dwell_time_seconds_060',
    'total_lead_dwell_time_seconds_060',
    'average_lead_dwell_time_seconds_060',
    'median_lead_dwell_time_seconds_060',
    'total_saved_listings_060',
    'total_shared_listings_060',
    'total_saved_searches_060',
    'total_shared_searches_060',
    #'srp_dominant_experience_type_web_060',
    #'srp_dominant_experience_type_mobile_web_060',
    #'srp_dominant_apps_type_others_060',
    'total_leads_submitted_060',
    'submitted_leads_for_rent_060',
    'submitted_leads_for_sale_060',
    'submitted_leads_not_for_sale_060',
    'ldp_dominant_segment_for_sale_090',
    'ldp_dominant_segment_not_for_sale_090',
    'ldp_dominant_segment_for_rent_090',
    'ldp_dominant_segment_no_segment_090',
    'total_ldp_page_views_090',
    'median_ldp_page_views_090',
    'average_ldp_page_views_090',
    'average_ldp_dwell_time_seconds_090',
    'total_ldp_dwell_time_seconds_090',
    'median_ldp_dwell_time_seconds_090',
    'total_distinct_listings_viewed_090',
    'total_listings_viewed_090',
    #'median_distinct_listings_viewed_090',
    #'average_distinct_listings_viewed_090',
    'median_listings_viewed_090',
    'average_listings_viewed_090',
    #'ldp_dominant_experience_type_web_090',
    #'ldp_dominant_experience_mobile_app_encoded_090',
    #'ldp_dominant_experience_type_mobile_web_090',
    #'ldp_dominant_experience_type_others_090',
    #'ldp_dominant_apps_type_ios_core_apps_090',
    #'ldp_dominant_apps_type_android_core_apps_090',
    #'ldp_dominant_apps_type_ios_rentals_apps_090',
    #'ldp_dominant_apps_type_android_rentals_apps_090',
    #'ldp_dominant_apps_type_others_090',
    'total_searches_090',
    'median_searches_090',
    'average_searches_090',
    'total_srp_dwell_time_seconds_090',
    'average_srp_dwell_time_seconds_090',
    'median_srp_dwell_time_seconds_090',
    'total_lead_dwell_time_seconds_090',
    'average_lead_dwell_time_seconds_090',
    'median_lead_dwell_time_seconds_090',
    'total_saved_listings_090',
    'total_shared_listings_090',
    'total_saved_searches_090',
    'total_shared_searches_090',
    #'srp_dominant_experience_type_web_090',
    #'srp_dominant_experience_type_mobile_web_090',
    #'srp_dominant_apps_type_others_090',
    'total_leads_submitted_090',
    'submitted_leads_for_rent_090',
    'submitted_leads_for_sale_090',
    'submitted_leads_not_for_sale_090'
]


sql_query_base = \
    """    
        select 
            DAY_PARTITION.member_id as member_id_PARTITION,
            DAY_PARTITION.snapshot_date_mst_yyyymmdd as snapshot_date_mst_yyyymmdd_PARTITION,
            (case when trim(DAY_PARTITION.ldp_dominant_segment) = 'for sale' then  1 else 0 end) as ldp_dominant_segment_for_sale_PARTITION,
            (case when trim(DAY_PARTITION.ldp_dominant_segment) = 'not for sale' then 1 else 0 end) as ldp_dominant_segment_not_for_sale_PARTITION,
            (case when trim(DAY_PARTITION.ldp_dominant_segment) = 'for rent' then  1 else 0 end) as ldp_dominant_segment_for_rent_PARTITION,
            (case when trim(DAY_PARTITION.ldp_dominant_segment) = 'no_segment' then  1 else 0 end) as ldp_dominant_segment_no_segment_PARTITION,
            coalesce(DAY_PARTITION.total_ldp_page_views, 0) AS total_ldp_page_views_PARTITION,
            coalesce(DAY_PARTITION.median_ldp_page_views, 0) AS median_ldp_page_views_PARTITION,
            coalesce(DAY_PARTITION.average_ldp_page_views, 0) AS average_ldp_page_views_PARTITION,
            (case when coalesce(DAY_PARTITION.average_ldp_dwell_time_seconds, 0)>180 THEN 180 ELSE COALESCE(DAY_PARTITION.average_ldp_dwell_time_seconds, 0) END) AS average_ldp_dwell_time_seconds_PARTITION,
            (case when coalesce(DAY_PARTITION.total_ldp_dwell_time_seconds, 0)>180 THEN 180 ELSE COALESCE(DAY_PARTITION.total_ldp_dwell_time_seconds, 0) END) AS total_ldp_dwell_time_seconds_PARTITION,
            (case when coalesce(DAY_PARTITION.median_ldp_dwell_time_seconds, 0)>180 THEN 180 ELSE COALESCE(DAY_PARTITION.median_ldp_dwell_time_seconds, 0) END) AS median_ldp_dwell_time_seconds_PARTITION,
            coalesce(DAY_PARTITION.total_distinct_listings_viewed,  0) AS total_distinct_listings_viewed_PARTITION,
            coalesce(DAY_PARTITION.total_listings_viewed, 0) AS total_listings_viewed_PARTITION,
            coalesce(DAY_PARTITION.median_distinct_listings_viewed,  0) AS median_distinct_listings_viewed_PARTITION,
            coalesce(DAY_PARTITION.average_distinct_listings_viewed, 0) AS average_distinct_listings_viewed_PARTITION,
            coalesce(DAY_PARTITION.median_listings_viewed, 0) AS median_listings_viewed_PARTITION,
            coalesce(DAY_PARTITION.average_listings_viewed, 0) AS average_listings_viewed_PARTITION,
            (case when trim(DAY_PARTITION.ldp_dominant_experience_type) = 'web' then  1 else  0 end) as ldp_dominant_experience_type_web_PARTITION,
            (case when trim(DAY_PARTITION.ldp_dominant_experience_type) = 'mobile apps'  then  1 else  0 end) as ldp_dominant_experience_mobile_app_encoded_PARTITION,
            (case when trim(DAY_PARTITION.ldp_dominant_experience_type) = 'mobile web'  then  1 else  0 end) as ldp_dominant_experience_type_mobile_web_PARTITION,
            (case when trim(DAY_PARTITION.ldp_dominant_experience_type) = 'others'  then  1 else  0 end) as ldp_dominant_experience_type_others_PARTITION,
            (case when trim(DAY_PARTITION.ldp_dominant_apps_type) = 'ios core apps' then  1 else  0 end) as ldp_dominant_apps_type_ios_core_apps_PARTITION,
            (case when trim(DAY_PARTITION.ldp_dominant_apps_type) = 'android core apps' then  1 else  0 end) as ldp_dominant_apps_type_android_core_apps_PARTITION,
            (case when trim(DAY_PARTITION.ldp_dominant_apps_type) = 'ios rentals apps' then  1 else  0 end) as ldp_dominant_apps_type_ios_rentals_apps_PARTITION,
            (case when trim(DAY_PARTITION.ldp_dominant_apps_type) = 'android rentals apps' then  1 else  0 end) as ldp_dominant_apps_type_android_rentals_apps_PARTITION,
            (case when trim(DAY_PARTITION.ldp_dominant_apps_type) = 'others' then  1 else  0 end) as ldp_dominant_apps_type_others_PARTITION,
            coalesce(DAY_PARTITION.total_searches, 0) AS total_searches_PARTITION,
            coalesce(DAY_PARTITION.median_searches, 0) AS median_searches_PARTITION,
            coalesce(DAY_PARTITION.average_searches, 0) AS average_searches_PARTITION,
            (case when coalesce(DAY_PARTITION.total_srp_dwell_time_seconds, 0)>180 THEN 180 ELSE COALESCE(DAY_PARTITION.total_srp_dwell_time_seconds, 0) END) AS total_srp_dwell_time_seconds_PARTITION,
            (case when coalesce(DAY_PARTITION.average_srp_dwell_time_seconds, 0)>180 THEN 180 ELSE COALESCE(DAY_PARTITION.average_srp_dwell_time_seconds, 0) END) AS average_srp_dwell_time_seconds_PARTITION,
            (case when coalesce(DAY_PARTITION.median_srp_dwell_time_seconds, 0)>180 THEN 180 ELSE COALESCE(DAY_PARTITION.median_srp_dwell_time_seconds, 0) END) AS median_srp_dwell_time_seconds_PARTITION,
            (case when coalesce(DAY_PARTITION.total_lead_dwell_time_seconds, 0)>180 THEN 180 ELSE COALESCE(DAY_PARTITION.total_lead_dwell_time_seconds, 0) END) AS total_lead_dwell_time_seconds_PARTITION,
            (case when coalesce(DAY_PARTITION.average_lead_dwell_time_seconds, 0)>180 THEN 180 ELSE COALESCE(DAY_PARTITION.average_lead_dwell_time_seconds, 0) END) AS average_lead_dwell_time_seconds_PARTITION,
            (case when coalesce(DAY_PARTITION.median_lead_dwell_time_seconds, 0)>180 THEN 180 ELSE COALESCE(DAY_PARTITION.median_lead_dwell_time_seconds, 0) END) AS median_lead_dwell_time_seconds_PARTITION,
            coalesce(DAY_PARTITION.total_saved_listings, 0) AS total_saved_listings_PARTITION,
            coalesce(DAY_PARTITION.total_shared_listings, 0) AS total_shared_listings_PARTITION,
            coalesce(DAY_PARTITION.total_saved_searches, 0) AS total_saved_searches_PARTITION,
            coalesce(DAY_PARTITION.total_shared_searches, 0) AS total_shared_searches_PARTITION,
            (case when trim(DAY_PARTITION.srp_dominant_experience_type) = 'web' then  1 else  0 end) as srp_dominant_experience_type_web_PARTITION,
            (case when trim(DAY_PARTITION.srp_dominant_experience_type) = 'mobile web' then  1 else  0 end) as srp_dominant_experience_type_mobile_web_PARTITION,
            (case when trim(DAY_PARTITION.srp_dominant_apps_type) = 'others' then  1 else  0 end) as srp_dominant_apps_type_others_PARTITION,
            coalesce(DAY_PARTITION.total_leads_submitted, 0) AS total_leads_submitted_PARTITION,
            coalesce(DAY_PARTITION.submitted_leads_for_rent, 0) AS submitted_leads_for_rent_PARTITION,
            coalesce(DAY_PARTITION.submitted_leads_for_sale, 0) AS submitted_leads_for_sale_PARTITION,
            coalesce(DAY_PARTITION.submitted_leads_not_for_sale, 0) AS submitted_leads_not_for_sale_PARTITION
        from global_temp.DAY_PARTITION as DAY_PARTITION
    """

sql_query_training_set = \
    """
        select
            coalesce(member_id_001,member_id_007,member_id_030,member_id_060,member_id_090) as member_id,
            coalesce(snapshot_date_mst_yyyymmdd_001,snapshot_date_mst_yyyymmdd_007,snapshot_date_mst_yyyymmdd_030,snapshot_date_mst_yyyymmdd_060,snapshot_date_mst_yyyymmdd_090 ) as snapshot_date_mst_yyyymmdd,
            month(coalesce(to_date(snapshot_date_mst_yyyymmdd_001, 'yyyyMMdd'),
                    to_date(snapshot_date_mst_yyyymmdd_007, 'yyyyMMdd'), 
                    to_date(snapshot_date_mst_yyyymmdd_030, 'yyyyMMdd'), 
                    to_date(snapshot_date_mst_yyyymmdd_060, 'yyyyMMdd'), 
                    to_date(snapshot_date_mst_yyyymmdd_090, 'yyyyMMdd'))) as snapshot_month,
            dayofmonth(coalesce(to_date(snapshot_date_mst_yyyymmdd_001, 'yyyyMMdd'),
                    to_date(snapshot_date_mst_yyyymmdd_007, 'yyyyMMdd'), 
                    to_date(snapshot_date_mst_yyyymmdd_030, 'yyyyMMdd'), 
                    to_date(snapshot_date_mst_yyyymmdd_060, 'yyyyMMdd'), 
                    to_date(snapshot_date_mst_yyyymmdd_090, 'yyyyMMdd'))) as snapshot_day_of_month,
            dayofweek(coalesce(to_date(snapshot_date_mst_yyyymmdd_001, 'yyyyMMdd'),
                    to_date(snapshot_date_mst_yyyymmdd_007, 'yyyyMMdd'), 
                    to_date(snapshot_date_mst_yyyymmdd_030, 'yyyyMMdd'), 
                    to_date(snapshot_date_mst_yyyymmdd_060, 'yyyyMMdd'), 
                    to_date(snapshot_date_mst_yyyymmdd_090, 'yyyyMMdd'))) as snapshot_day_of_week,
            *
        from global_temp.joined_df as joined_df 
    """

num_smoke_tests = 20